### ISSUE TITLE
bash: tpm: command not found

### ISSUE THREAD

**Issue by shabbir-dhangot** [totaljs/flowboard#3]
Running make.sh command is throwing error. 

How to run as I updated something into source and want to create package. 

bash: tpm: command not found

**Comment by petersirka** [comment]
Hi, you need to install Total.js as a global module:

- `$ npm install -g total.js`

**Comment by shabbir-dhangot** [comment]
I am getting below error while executing make.sh. FYI I am using windows 

    Can't find file flowboard-master.package
    bash: tpm: command not found
    mv: cannot stat 'flowboard-master.package': No such file or directory

**Comment by petersirka** [comment]
Then you need to write `make.sh`.

- `tpm` makes a package/bundle from the directory (it must work)
- other things you need to customize

**Comment by petersirka** [comment]
~~to write~~ --> `to rewrite`

**Comment by shabbir-dhangot** [comment]
Thanx @petersirka, I am able to make package now. Its not recognizing in normal command prompt. I executed command directly in the nodejs command prompt and its working.
